### ISSUE TITLE
Add to ROS Kinetic Index

### ISSUE THREAD

**Issue by EpicWolverine** [wjwwood/serial_utils#1]
I got it complied on my own machine without change under Kinetic (though I don't think it's "installed"), but I would appreciate it if you could update the package on the ROS package manager to support Kinetic so we can use `rosdep` to automatically find and install it as a dependency.

**Comment by nlieb** [comment]
This is an ongoing issue for us. Any updates @wjwwood ?

**Comment by wjwwood** [comment]
I just released it into Kinetic: https://github.com/ros/rosdistro/pull/16766

**Comment by EpicWolverine** [comment]
Thank you!
